# Generated by Django 4.2.6 on 2023-10-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150, null=True)),
                ("address", models.CharField(max_length=300, null=True)),
                ("password", models.CharField(max_length=150)),
            ],
        ),
    ]
