# Generated by Django 4.2.6 on 2023-10-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=150)),
                ("produc_price", models.IntegerField(max_length=10)),
                ("product_image", models.ImageField(upload_to="products")),
                ("product_category", models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
