# Generated by Django 4.2.6 on 2023-10-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="produc_price",
            field=models.IntegerField(),
        ),
    ]
